### ISSUE TITLE
Broken shebang line in release

### ISSUE THREAD

**Issue by jamesscottbrown** [sboltools/sboltools#8]
Makedist [adds a shebang line](https://github.com/sboltools/sboltools/blob/5cfd5111e55fb241461c7493d01d06cb00c99c97/makedist.js#L7) `#!/usr/bin/env node --no-deprecation` to the generated `sbol` file that is released.

However, running this gives the error:

    /usr/bin/env: 'node --no-deprecation': No such file or directory

since `env` treats `node --no-deprecation` as a single argument, rather than realising that it is the name of a command and an argument to be provided to that command.

One alternative would be a wrapper script that sets 

```bash
EXPORT NODE_OPTIONS='--no-deprecation' 
```

before running `sbol`.

**Comment by jamesamcl** [comment]
I've hopefully fixed this using `env -S` in the shebang:

https://unix.stackexchange.com/a/477651/17565

Seems to work on Linux and Mac. Thanks for reporting.

**Comment by jamesscottbrown** [comment]
This works fine on Ubuntu 20.04, but a machine running Ubuntu 18.04 (not the most recent LTS release, but one which will still be under "standard support" until 2023) has 

```
$ env --version
env (GNU coreutils) 8.28
```

which was released before the `-S` option was added.
